name: format, build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-solutions-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: fetch dependencies
      run: |
        sudo apt-get install libgtest-dev clang-format clang-tidy
    - name: clang format
      run : |
        script/format.sh
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: make
      run: |
        cd build
        make
    - name: test
      run: |
        cd build
        ctest --output-on-failure --output-junit test_results.xml